[package]
name = "kitbag-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Model and engine for kitbag"

[dependencies]
base64 = "0.22"
serde.workspace = true
sha2 = "0.10"
thiserror.workspace = true
